chore: fix some function names
ledgerwatch/erigon pull request #10568
Opened 2024-05-31 07:07 UTC by zoupingshi

2024-05-31 11:38 UTC, shohamc1 requested changes

2024-05-31 11:38 UTC, shohamc1 commented on cl/persistence/state/historical_states_reader/historical_states_reader.go
>  func (r *HistoricalStatesReader) ReadPartecipations(tx kv.Tx, slot uint64) (*solid.BitList, *solid.BitList, error) {
```suggestion
func (r *HistoricalStatesReader) ReadParticipations(tx kv.Tx, slot uint64) (*solid.BitList, *solid.BitList, error) {
```

2024-06-02 12:34 UTC, AskAlexSharov approved these changes

2024-06-07 04:53 UTC, AskAlexSharov commented
@zoupingshi need fix CI errors

2024-06-21 02:02 UTC, AskAlexSharov commented
red ci - closing

2024-06-21 02:02 UTC, closed without merging