chore: remove repetitive word
ledgerwatch/erigon pull request #10624
Opened 2024-06-05 08:59 UTC by lido333

2024-06-05 14:42 UTC, yperbasis approved these changes

2024-06-05 14:45 UTC, yperbasis requested changes
it should probably be "part of the state the transition modifies"

2024-06-05 16:12 UTC, lido333 commented
> it should probably be "part of the state the transition modifies"

fixed @yperbasis

2024-06-07 04:52 UTC, AskAlexSharov approved these changes

2024-06-12 10:01 UTC, closed without merging