Avoid using MemBatch in `Validaet
ledgerwatch/erigon pull request #10678
Opened 2024-06-09 14:22 UTC by Giulio2002

2024-06-09 18:33 UTC, Giulio2002 commented on turbo/execution/eth1/forkchoice.go
> -		}
this is useless btw

2024-06-09 18:34 UTC, Giulio2002 commented on erigon-lib/state/state_changeset.go
> +const diffChunkLen = 8*1024 - 32
had to move it here so that I can incorporate it with Flushing of domains

2024-06-10 02:32 UTC, AskAlexSharov requested changes
I don't understand how ValidateChain can do `BeginRw`. 
What if node does execution at this time? 
It means we have less time for pruning? 
What if you need validate 2 forks? 
Or did you mean `BeginRo`?
Plz add this info in description of PR, otherwise hard to understand the intent.

2024-06-10 10:42 UTC, Giulio2002 commented
Ok, so the "Write" part of RwTx is only used for unwinding beforehand. If you look at the code the RwTx is rollbacked right after `ValidatePayload`. It does not mean we have less time for pruning the flushing is done through `SharedDomains` we keep it and use that to `Flush`, so functionally, it is as if we had diff like before but in the form of SharedDomain's writers. if you need to validate 2 big forks, you can do that with no issue, because it is functionally equivalent to the previous one.

Regarding intent, Intent are:
*  to remove the `FlushExtendingFork` timing, before we were flushing domains on membatch and then flush membatch onto a RwTx, this was quite expensive in terms of performance
* Make the routine more stable, MemoryMutation is quite buggy, so it removes one of the things we have to worry about.

2024-06-10 10:43 UTC, awskii commented
So this issue fixes DupSort issue in MemBatch causing
`[5/7 Execution] ExecV3: loadIntoTable : fn error: prune history commitment got invalid txNum: found 2434374999 != 2433726825 wanted"`

2024-06-10 10:44 UTC, Giulio2002 commented
yes that too

2024-06-11 01:59 UTC, AskAlexSharov approved these changes

2024-06-11 02:11 UTC, merged