Basetxid type extraction
ledgerwatch/erigon pull request #10701
Opened 2024-06-11 19:44 UTC by awskii

2024-06-12 04:32 UTC, AskAlexSharov requested changes

2024-06-12 04:32 UTC, AskAlexSharov commented on core/types/block.go
> +func CapBaseTxID(tx int) uint64 {
`CapBaseTxID` - don't understand func name (can't translate).

2024-06-12 04:32 UTC, AskAlexSharov commented on core/types/block.go
> +// Represents original transaction number in blockchain (do not includes system txs in block)
1. ` Represents original transaction number in blockchain` - no. by naming (see `Dev.md`): 
- Num - it's blockchain-related number - same on all nodes
- ID - it's our internal auto-increment - not related to blockchain and different on all nodes. 

2. `BaseTxID` let's rename it to `BaseTxnID`. Also let's rename `txID` to `txnID`. (also by naming - see `Dev.md`)

2024-06-12 04:32 UTC, AskAlexSharov commented on core/types/block.go
> +//	0 - base tx/systemBegin
sustem transactions are used to write history of state changes done by consensus (not by eth-transactions) - for example "miner rewards"

2024-06-14 02:27 UTC, AskAlexSharov approved these changes

2024-06-25 16:33 UTC, awskii commented
amoy file matches. waiting for building files for sepolia to be sure.

2024-06-27 16:32 UTC, awskii commented
I triple-checked with amoy and double with sepolia, headers/bodies/txns .seg come out all the same, state files also matched for sepolia

2024-06-28 00:44 UTC, merged