Changing Caplin Finality Checkpoint API call to match spec
ledgerwatch/erigon pull request #10843
Opened 2024-06-21 13:08 UTC by angusscott

Changing the response for finality checkpoints to match the Ethereum specification by removing the _checkpoint postfix

[https://ethereum.github.io/beacon-APIs/#/Beacon/getStateFinalityCheckpoints]( https://ethereum.github.io/beacon-APIs/#/Beacon/getStateFinalityCheckpoints)

2024-06-21 21:28 UTC, Giulio2002 requested changes

2024-06-21 21:28 UTC, Giulio2002 commented on cl/phase1/core/state/raw/state.go
> -		"justification_bits":            b.justificationBits,
this is actually correct

2024-06-24 07:02 UTC, angusscott commented on cl/phase1/core/state/raw/state.go
> -		"justification_bits":            b.justificationBits,
Yes, reviewed and agreed, reverted back

2024-06-24 09:06 UTC, Giulio2002 approved these changes

2024-06-24 09:30 UTC, merged