Forprefix remove
ledgerwatch/erigon pull request #10883
Opened 2024-06-24 12:31 UTC by JkLondon

closes #10765

2024-06-24 13:20 UTC, AskAlexSharov requested changes

2024-06-24 13:20 UTC, AskAlexSharov commented on core/rawdb/accessors_chain.go
> +	kvs, err := db.Prefix(kv.Headers, prefix)
defer kvs.Close()

2024-06-24 13:20 UTC, AskAlexSharov commented on erigon-lib/kv/kv_interface.go
> +	Prefix(table string, prefix []byte) (iter.KV, error)
We already have Range method in interface. Use it plz.

2024-06-25 05:45 UTC, JkLondon commented on core/rawdb/accessors_chain.go
> +	kvs, err := db.Prefix(kv.Headers, prefix)
done

2024-06-28 04:14 UTC, AskAlexSharov approved these changes

2024-06-28 04:14 UTC, merged