E3: Fixed --chain=dev
ledgerwatch/erigon pull request #10921
Opened 2024-06-26 13:59 UTC by Giulio2002

2024-06-26 14:02 UTC, Giulio2002 commented
close #10921

2024-06-26 16:06 UTC, yperbasis requested changes

2024-06-26 16:06 UTC, yperbasis commented on eth/backend.go
>  		}
Plz add here (i.e. if not Bor and not Clique)
```
else {
  s.logger.Error("mining is not supported after the Merge")
  return errors.New("mining is not supported after the Merge")
}
```
to ensure that this old-school mining is not enabled for Ethereum mainnet & Gnosis Chain. See also Issue #10716.

2024-06-26 16:10 UTC, yperbasis commented on eth/backend.go
> -					hasWork = s.chainConfig.Bor == nil
Why this change?

2024-06-27 12:53 UTC, yperbasis approved these changes

2024-06-27 13:18 UTC, merged