added flag to integration
ledgerwatch/erigon pull request #11093
Opened 2024-07-09 17:02 UTC by JkLondon

closes #11019 but not sure is this enough

2024-07-10 02:00 UTC, AskAlexSharov requested changes
Need pass value of this flag to chaindata db - when opening it

2024-07-10 02:00 UTC, AskAlexSharov commented on cmd/integration/commands/flags.go
> +	cmd.Flags().BoolVar(&dbWriteMap, "db.writemap", true, "Enable WRITE_MAP feauture for fast database writes and fast commit times")
Use existing flag variable. Like: utils.DataDirFlag

2024-07-10 13:51 UTC, JkLondon commented on cmd/integration/commands/flags.go
> +	cmd.Flags().BoolVar(&dbWriteMap, "db.writemap", true, "Enable WRITE_MAP feauture for fast database writes and fast commit times")
done

2024-07-11 03:08 UTC, AskAlexSharov approved these changes

2024-07-11 03:08 UTC, merged