rlpgen: step 1
ledgerwatch/erigon pull request #11112
Opened 2024-07-11 04:33 UTC by AskAlexSharov

- no behavior changes
- move encbuffer and encreader to `encbuffer.go`
- copy-paste rlpgen package

2024-07-11 08:44 UTC, JkLondon requested changes
need to change license from go-ethereum to Erigon

2024-07-11 08:44 UTC, JkLondon commented on rlp/encbuffer.go
> +// Copyright 2022 The go-ethereum Authors
need to change license

2024-07-12 04:25 UTC, AskAlexSharov commented on rlp/encbuffer.go
> +// Copyright 2022 The go-ethereum Authors
done

2024-07-15 04:41 UTC, JkLondon approved these changes

2024-07-15 04:41 UTC, merged