txpool: Don't propagate transactions with duplicate authorizations
ledgerwatch/erigon pull request #13137
Opened 2024-12-17 07:44 UTC by shohamc1

Fixes #11763

Tests adapted from: https://github.com/lightclient/go-ethereum/commit/fe828ff59ecaf16ed67db1735e481aaa78dfb472

Futher work: use (remote/local) block reader to get latest account nonce as set code txns may increment nonce more than once.

2025-01-09 03:13 UTC, shohamc1 commented on txnprovider/txpool/pool_txn_parser.go
> +			slot.AuthRaw = append(slot.AuthRaw, payload[rawStart:rawEnd+1])
Is this ok? Any better way to do this?

Also need another check on if we really need the +1 here.

2025-01-09 09:29 UTC, taratorio commented
@shohamc1 fyi there are linter errors

2025-01-13 12:23 UTC, yperbasis requested changes

2025-01-13 12:23 UTC, yperbasis commented on txnprovider/txpool/pool_txn_parser.go
> +			slot.AuthRaw = append(slot.AuthRaw, payload[rawStart:rawEnd+1])
Better use `libcommon.CopyBytes`. Please also double check whether +1 is needed and add a test for it.

2025-01-13 14:47 UTC, yperbasis commented on txnprovider/txpool/pool_txn_parser.go
> +			slot.AuthRaw = append(slot.AuthRaw, common.CopyBytes(payload[rawStart:rawEnd]))
There's no need for `append` - simply `CopyBytes`

2025-01-13 14:51 UTC, yperbasis commented on txnprovider/txpool/pool.go
> +	for _, mt := range minedTxns.Txns {
Better move this into `removeMined`

2025-01-13 14:54 UTC, yperbasis approved these changes

2025-01-13 16:09 UTC, merged

2025-01-15 09:35 UTC, somnathb1 commented
@shohamc1 Please back-port this to `release/2.61`