implement get proof rpc endpoint
ledgerwatch/erigon pull request #13291
Opened 2024-12-31 18:44 UTC by shotasilagadze

#13201

2025-01-01 21:59 UTC, Giulio2002 commented
Add unit tests + remove printlns. @awskii will give a more meaningful review tho. this is not my domain

2025-01-06 12:34 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +	domains, err := libstate.NewSharedDomains(txBatch2, log.New())
can use rotx directly, no need to add membatch on top

2025-01-06 12:41 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +	sdCtx := libstate.NewSharedDomainsCommitmentContext(domains, commitment.ModeUpdate, commitment.VariantHexPatriciaTrie)
also i do not like this export of Trie from CommitmentContext. Instead, needed method should be supported via CommitmentContext itself.

2025-01-06 12:46 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +	accountProof, _, err := proofTrie.Prove(crypto.Keccak256(address.Bytes()), 0, false)
what actually stops us from generating proof during fold?

2025-01-06 12:48 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +	accountProof, _, err := proofTrie.Prove(crypto.Keccak256(address.Bytes()), 0, false)
i mean besides of ready-to-go api? do we lack some information during fold phase for that?

2025-01-07 09:29 UTC, antonis19 commented on erigon-lib/commitment/hex_patricia_hashed.go
> +func (hph *HexPatriciaHashed) GenerateTouchedKeyTrie(ctx context.Context, updates *Updates, expectedRootHash []byte, logPrefix string) (touchedKeyTree *trie.Trie, rootHash []byte, err error) {
Not necessary to duplicate code as you can directly call `GenerateWitness` and get the desired result.

2025-01-07 09:30 UTC, antonis19 commented on erigon-lib/trie/proof.go
> +func (t *Trie) Prove(key []byte, fromLevel int, storage bool) ([][]byte, []byte, error) {
Not necessary to rely on `Prove` to get the storage value as it can easily be retrieved via stateReader.

2025-01-07 09:30 UTC, antonis19 commented on erigon-lib/trie/proof.go
> +				fromLevel--
Why was this change needed?

2025-01-07 09:31 UTC, antonis19 commented on turbo/jsonrpc/eth_call_test.go
> -		},
Why are these tests disabled?

2025-01-07 09:35 UTC, antonis19 commented on turbo/jsonrpc/eth_call_test.go
> -		},
what about `"currentBlockNoAccountMissingState"` ?  that seems relevant for us

2025-01-07 10:44 UTC, antonis19 commented on turbo/jsonrpc/eth_call.go
> +		if proof.StorageHash.Cmp(libcommon.BytesToHash(commitment.EmptyRootHash)) != 0 {
Can move this above `proofTrie.Prove` to avoid calling Prove in this case.

2025-01-07 10:45 UTC, antonis19 commented on turbo/jsonrpc/eth_call.go
> +		if proof.StorageHash.Cmp(libcommon.BytesToHash(commitment.EmptyRootHash)) != 0 {
Oh but I guess you are relying on `Prove` to get the value, so it might not be possible to skip that call.

2025-01-09 17:03 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +	return api.getProof(ctx, address, storageKeys, rpc.BlockNumberOrHashWithNumber(rpc.BlockNumber(latestBlock)), api.db, api.logger)
why not to pass already opened RoTx?

2025-01-09 17:04 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +	blockNr, _, _, err := rpchelper.GetCanonicalBlockNumber(ctx, blockNrOrHash, roTx, api._blockReader, api.filters)
this was recently fetched at line 348

2025-01-09 17:05 UTC, awskii commented on erigon-lib/state/domain_shared.go
> +func (sdc *SharedDomainsCommitmentContext) GenerateTouchedKeyTrie(ctx context.Context, expectedRoot []byte, logPrefix string) (proofTrie *trie.Trie, rootHash []byte, err error) {
Why just not `Witness`?

2025-01-09 17:06 UTC, awskii commented on erigon-lib/trie/proof.go
> +				fromLevel--
how are we sure len(key) always 1?

2025-01-09 17:09 UTC, awskii requested changes

2025-01-09 17:09 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +	proofTrie, proofRootHash, err := sdCtx.GenerateTouchedKeyTrie(ctx, header.Root[:], "eth_getProof")
if we pass expected root, why then we do not check that root matches and do not return error from Witnesses generation function?

2025-01-09 17:09 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +		if !bytes.Equal(proofRootHash, header.Root[:]) {
again why verify hash outside if we passing expected root inside

2025-01-16 13:26 UTC, antonis19 commented on erigon-lib/trie/proof.go
> +func (t *Trie) Prove(key []byte, fromLevel int, storage bool) ([][]byte, []byte, error) {
As we discussed, I's suggest not returning the value bytes since we don't want the function to do more than it should. If you need the value either use a StateReader, or write another function to traverse the trie and get the value. I did this on my branch:

```Go
func (t *Trie) GetAccountNode(key []byte) (value *AccountNode, gotValue bool) {
	hex := keybytesToHex(key)
	return t.getAccount(t.RootNode, hex, 0)
}
```

2025-01-20 16:05 UTC, antonis19 approved these changes

2025-01-21 13:41 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +	a := new(big.Int).SetInt64(0)
but zero big int is still empty hexutility.Big, so could not init?

2025-01-21 13:49 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +		n := new(big.Int)
so instead can do  big.NewInt(0)

2025-01-21 13:56 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +		fullKey = append(fullKey, crypto.Keccak256(address.Bytes())...)
this is `commitment.KeyToHexNibbleHash`

2025-01-21 14:04 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +		proof.StorageProof[i].Value = (*hexutil.Big)(unsafe.Pointer(n))
aren't *big.Int convertible to hexutil.Big without unsafe.Pointer? usage of unsafe could affect how gc assess lifetime of structure behind it, may be not the case here but still if can avoid this cast -- better to avoid

2025-01-21 14:07 UTC, awskii requested changes

2025-01-21 14:07 UTC, awskii commented on turbo/jsonrpc/eth_call_test.go
> +		// {
can uncomment and pass? or remove and add particular cases?

2025-01-23 12:12 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +			fmt.Printf("couldn't read account storage for the address %s\n", address.String())
imo using logger would be better

2025-01-23 12:16 UTC, awskii commented on turbo/jsonrpc/eth_call.go
> +		n.SetString(hex.EncodeToString(res), 16)
wait, if res is a slice of bytes, why convert it to string then parse string representation, can say `n.SetBytes(res)`

2025-01-23 12:17 UTC, awskii approved these changes

2025-01-24 07:16 UTC, merged