Added init functionality
ledgerwatch/erigon pull request #2626
Opened 2021-09-03 09:02 UTC by Uttam-Singhh

2021-09-03 09:09 UTC, AskAlexSharov commented on turbo/cli/make_app.go
> +	for _, name := range []string{"chaindata", "lightchaindata"} {
I think you don't need this loop. Because variable `name` not used anywhere and Erigon has no `lightchaindata`

2021-09-03 09:14 UTC, AskAlexSharov commented on turbo/cli/make_app.go
> +	nodeConfig.IPCPath = "erigon.ipc" // force-disable IPC endpoint
you need somehow use utils.DataDirFlag which you defined above
normally it's happening in `cmd/utils/flag.go:SetNodeConfig->setDataDir`

2021-09-03 10:16 UTC, AskAlexSharov requested changes
added couple comments: need support --datadir option, and remove ligthchaindata support.

2021-09-06 09:37 UTC, 0xKrishna commented
@AskAlexSharov Updated, Please review again.

2021-09-07 06:44 UTC, merged