Decoding incarnation and Tests
ledgerwatch/erigon pull request #2727
Opened 2021-09-25 15:14 UTC by enriavil1

External functions for accounts, which decodes incarnations directly. Also wrote some tests for it too.

2021-09-25 19:07 UTC, Giulio2002 requested changes

2021-09-25 19:07 UTC, Giulio2002 commented on core/types/accounts/account_test.go
> +func testIncarnationWithCode(t *testing.T) {
This test is useless, will never check for code

2021-09-25 19:09 UTC, Giulio2002 requested changes
One more thing, you are testing empty incarnations and no incarnation, please provide a test where account has incarnation different than 0

2021-09-26 12:58 UTC, merged

2021-09-26 12:58 UTC, AskAlexSharov commented
merging. 
better check errors in tests (which returned by DecodeIncarnationFromStorage)