adding engine_ExchangeTransitionConfigurationV1
ledgerwatch/erigon pull request #3454
Opened 2022-02-09 10:35 UTC by enriavil1

engine_ExchangeTransisitionConfigurationV1 is called periodically by the CL to check if the EL has the correct configurations.

2022-02-13 19:20 UTC, Giulio2002 requested changes

2022-02-13 19:20 UTC, Giulio2002 commented on cmd/rpcdaemon/commands/engine_api.go
> +	if terminalTotalDifficulty != transitionConfiguration.TerminalTotalDifficulty.ToInt() {
TTD, is likely too big to be stored in an Int, try with `terminalTotalDifficulty.Cmp(transitionConfiguration.TerminalTotalDifficulty) != 0`

2022-02-13 19:20 UTC, Giulio2002 commented on params/config.go
> +	return fmt.Sprintf("{ChainID: %v Homestead: %v DAO: %v DAOSupport: %v EIP150: %v EIP155: %v EIP158: %v Byzantium: %v Constantinople: %v Petersburg: %v Istanbul: %v, Muir Glacier: %v, Berlin: %v, Lon
remove this, we do not want this on startup all the time, not significant data.

2022-02-13 19:20 UTC, Giulio2002 commented on params/config.go
> +	TerminalTotalDifficulty *big.Int        `json:"terminalTotalDifficulty,omitempty"` // The merge happens when terminal total difficulty is reached
as you can see you using * which makes the field optional, be careful, see comment above about nil-checking

2022-02-13 19:20 UTC, Giulio2002 commented on cmd/rpcdaemon/commands/engine_api.go
> +	terminalTotalDifficulty := chainConfig.TerminalTotalDifficulty
Be careful, check if `chainConfig.TerminalTotalDifficulty` is set in chain config, aka. `chainConfig.TerminalTotalDifficulty != nil` if you use nil value the daemon will panic

2022-02-13 19:20 UTC, Giulio2002 commented on cmd/rpcdaemon/commands/engine_api.go
> +	if *chainConfig.TerminalBlockHash != transitionConfiguration.TerminalBlockHash {
check if `chainConfig.TerminalBlockHash == nil`, that will do so that you do not use erroneously a nil value and panic the daemon

2022-02-14 08:17 UTC, yperbasis requested changes
Git submodules (libmdbx & erigon-snapshots) should not change.

2022-02-14 08:18 UTC, yperbasis commented on params/config.go
> +	return fmt.Sprintf("{ChainID: %v Homestead: %v DAO: %v DAOSupport: %v EIP150: %v EIP155: %v EIP158: %v Byzantium: %v Constantinople: %v Petersburg: %v Istanbul: %v, Muir Glacier: %v, Berlin: %v, Lon
No need to remove the last comma

2022-02-14 11:53 UTC, yperbasis commented on cmd/rpcdaemon/commands/engine_api.go
> +	TerminalBlockNumber     hexutil.Uint64 `json:"terminalBlockNumber" gencodec:"requiered"`
Typo in requiered

2022-02-15 07:17 UTC, yperbasis commented on params/config.go
> +	TerminalBlockNumber     *hexutil.Uint64 `json:"terminalBlockNumber,omitempty"`     // The block number of the last POW block
Better use `*big.Int` instead of `*hexutil.Uint64` here for `TerminalBlockNumber` for consistency (see `BerlinBlock`, `LondonBlock`, etc).

2022-02-15 07:22 UTC, yperbasis commented on cmd/rpcdaemon/commands/engine_api.go
> +	ExchangeTransitionConfigurationV1(ctx context.Context, transitionConfiguration TransitionConfiguration, terminalBlockNumber hexutil.Uint64) (TransitionConfiguration, error)
`terminalBlockNumber` is already a part of `transitionConfiguration`, no need to make it into a separate argument. See the [request spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#request-3) of `engine_exchangeTransitionConfigurationV1`.

2022-02-15 08:03 UTC, yperbasis approved these changes

2022-02-15 09:30 UTC, merged