Update removed unreachable golangci-lint from `make clean`
ledgerwatch/erigon pull request #3461
Opened 2022-02-09 18:45 UTC by y0wl

Two lines above the removed line removes `golangci-lint`, even if it was previously downloaded with `make lintci-deps` which would always cause an error when attempting to call `golangci-lint`. I do not believe there is much use in running the linter in the `clean` target anyway.

2022-02-10 01:00 UTC, AskAlexSharov requested changes
1. Actually use-case exists: see `rules.go` file - this is hand-crafted linters based on `ruleguard`. And currently golangcilint does cache such rules - and only way to apply new rules.go is to run `golangcilint clean`. Probably it will improve in future versions of golangcilint.  
2. It's easy to test "if file exists" before exec it

2022-02-10 15:36 UTC, y0wl commented
> 1. Actually use-case exists: see `rules.go` file - this is hand-crafted linters based on `ruleguard`. And currently golangcilint does cache such rules - and only way to apply new rules.go is to run `golangcilint clean`. Probably it will improve in future versions of golangcilint.
> 2. It's easy to test "if file exists" before exec it

I'm confused as to whenever it will exist, they `rm -rf` the directory it lives in before attempting to run it. Would the solution be avoid removing it earlier in the `clean` target and then running if it exists?

2022-02-10 20:37 UTC, y0wl commented
The new deletion command removes all directories and files under build other than the `golangci-lint` path. This is unnecessary since the only location populated is in `/build/bin/*`, but it's more versatile for the future. 

It can be changed to `find ./build ! -path "./build/bin/golangci-lint" -type f -delete` if we don't mind dropping the removal of empty directories. Or maybe even better with two lines, the first for files the second for the empty directories left behind with the `-empty` flag.

2022-02-10 20:49 UTC, y0wl commented
The `clean` target will now leave behind the `golangci-lint` binary if it exists. It will also call `golangci-lint cache clean` if it exists.

2022-02-12 08:25 UTC, AskAlexSharov requested changes
I just thought about it one more time: 
Let's remove "golangci-lint cache clean" from Makefile, because it's too rare case and adding complexity

2022-02-14 04:11 UTC, AskAlexSharov commented
Hi. Thank you for PR. I just removed "golangci-lint cache clean" from "make clean". Closing.

2022-02-14 04:11 UTC, closed without merging

2022-02-14 19:08 UTC, y0wl commented
> Hi. Thank you for PR. I just removed "golangci-lint cache clean" from "make clean". Closing.

My original suggestion :)

Glad it's in :) thanks!