Fix disabled value for `--prune.*` flags
ledgerwatch/erigon pull request #4165
Opened 2022-05-16 11:25 UTC by leonardchinonso

Changes:
* Proceeded to check if other h, r, t or c flags for 'before' and 'older' are set before returning from the default state of --prune
Concern:
* Does the 'disabled' value for '--prune=' need to be updated if the '--prune.*' flags are set but the '--prune=' flag is not?

2022-05-16 12:58 UTC, AskAlexSharov commented
general rules:
1. do not allow users to change --prune flags after first node start
2. if user changed cli flags - advise what flags was before (because maybe he doesn't remember)
3. if any --prune* flag is set: means "pruning feature" is enabled. For example: if only `--prune.r.before=500` set, then only Receipts need to be pruned. 
4. `--prune=r` it's just shortcut for `--prune.r.older=90_000`, no special meaning

2022-05-16 13:00 UTC, AskAlexSharov commented
You can test next way: 
- create new node with some set of --prune* flags, restart node with another set of flags: Erigon must show error with advise to use flags from first run

2022-05-16 13:05 UTC, AskAlexSharov requested changes
Now if set only flag: `--prune.r.before=500`, erigon does show: 
`prune_flags="--prune= --prune.r.before=500"`

Let's do next way (if you don't have better idea):

- If only `--prune.r.before=500` set: show `prune_flags="--prune.r.before=500"`
- if only `--prune=r` set: show `prune_flags="--prune.r.older=90000"`
- if `--prune=r --prune.h.older=1000` set: show `prune_flags="--prune.r.older=90000 --prune.h.older=1000"`

2022-05-17 01:06 UTC, AskAlexSharov commented on ethdb/prune/storage_mode.go
> +	const defaultVal uint64 = 90000
It FullImmutabilityThreshold

2022-05-17 02:31 UTC, AskAlexSharov approved these changes

2022-05-17 02:31 UTC, merged

2022-05-17 08:54 UTC, leonardchinonso commented on ethdb/prune/storage_mode.go
> +	const defaultVal uint64 = 90000
Okay, thanks