Add eth_getBalanceChangesInBlock RPC endpoint
ledgerwatch/erigon pull request #4609
Opened 2022-07-02 18:37 UTC by tsutsu

2022-07-02 19:07 UTC, AlexeyAkhunov commented on cmd/rpcdaemon/commands/eth_api_test.go
> +	PrintChangedBalances(balances)
Would you be able to put couple of asserts here?

2022-07-04 10:56 UTC, mandrigin commented
@tsutsu please also update the REAMDE for rpcdaemon and include the new API method

2022-07-04 23:13 UTC, tjayrush commented
Should this be in the `eth_` namespace? I feel like that will come back to haunt you at some point. Isn't the `eth_` namespace reserved for things available across multiple clients and maybe even requiring an EIP?

2022-07-06 04:07 UTC, tsutsu commented
> Should this be in the `eth_` namespace? I feel like that will come back to haunt you at some point. Isn't the `eth_` namespace reserved for things available across multiple clients and maybe even requiring an EIP? I did a quick Google search. I didn't find it elsewhere. Maybe I missed it.

I agree; this isn't a standardized endpoint (and in fact wouldn't be supportable in other clients due to only being practical with a ChangeSet-like index) so shouldn't be under `eth_`. Wasn't sure of the correct namespace to put this under. Will change to whatever is suggested.

2022-07-06 08:14 UTC, mandrigin commented
@tsutsu let's add real test asserts and move it to `erigon_` for now

2022-07-06 08:17 UTC, mandrigin requested changes
(1) add assets to this tes
(2) move to `erigon_` namespace

2022-07-11 22:25 UTC, fatemebagherii commented
> (1) add assets to this tes (2) move to `erigon_` namespace

Here are some assertions: https://github.com/ledgerwatch/erigon/pull/4609/commits/25be3d63469839f4f79952efae86bf20a093248d
Are they sufficient?

2022-07-15 07:40 UTC, AskAlexSharov commented
@mandrigin let's merge?

2022-07-15 14:04 UTC, mandrigin approved these changes

2022-07-15 14:04 UTC, merged

2022-07-15 14:04 UTC, mandrigin commented
Done!