Optimized PoS header downloader
ledgerwatch/erigon pull request #4775
Opened 2022-07-21 06:23 UTC by Giulio2002

2022-07-21 07:54 UTC, mandrigin commented on turbo/stages/headerdownload/header_algos.go
> +	}
```suggestion
	parentHeight := 0
	if anchor.blockHeight > 0 {
		parentHeight = anchor.blockHeight - 1
	}
```

2022-07-21 15:21 UTC, yperbasis requested changes

2022-07-21 15:21 UTC, yperbasis commented on eth/stagedsync/stage_headers.go
> +		schedulePoSDownload(requestId, hashToDownload, headerNumber, s, cfg)
The names of the arguments to `schedulePoSDownload` are `hashToDownload`, `heightToDownload`. So the implication is that they refer to the same block, which was previously the case:
```
hashToDownload := header.ParentHash
heightToDownload := headerNumber - 1
```
But with this change they refer to different things (header's number and its _parent's_ hash). So please either revert this change (not the entire PR, just the `schedulePoSDownload` parameters part) or rename the params of `schedulePoSDownload`.

2022-07-22 08:17 UTC, yperbasis approved these changes

2022-07-22 09:07 UTC, merged