Eth2DeployBlockNumber function, update on Execution of Pruning
ledgerwatch/erigon pull request #4934
Opened 2022-08-04 11:58 UTC by TKartist

Eth2DeployBlockNumber function added to params.config file, and writeReceipt and ExecutionOfPrunningStage modified.

2022-08-04 13:35 UTC, AskAlexSharov requested changes

2022-08-04 13:35 UTC, AskAlexSharov commented on eth/stagedsync/stage_execute.go
> +		if params.Eth2DeployBlockNumber(cfg.chainConfig) >= blockNum {
Logic need to invert?

2022-08-04 13:35 UTC, AskAlexSharov commented on eth/stagedsync/stage_execute.go
> +		if s.ForwardProgress > params.Eth2DeployBlockNumber(cfg.chainConfig) {
Logic need to invert?

2022-08-04 13:35 UTC, AskAlexSharov commented on params/config.go
> +func Eth2DeployBlockNumber(c *ChainConfig) uint64 {
Maybe calc this value once when app start and adjust cfg.prune.Receipts according to this numbers?

2022-08-08 02:26 UTC, AskAlexSharov commented on eth/stagedsync/stage_execute.go
> +	depositeAddress := params.Eth2DeployBlockNumber(cfg.chainConfig)
I see on left side "Address" and on right side "blockNumber". Probably it's not address?

2022-08-09 12:51 UTC, Giulio2002 requested changes

2022-08-09 12:51 UTC, Giulio2002 commented on eth/stagedsync/stage_log_index.go
> -	if startBlock < pruneTo {
just change the pruneTo value

2022-08-09 12:51 UTC, Giulio2002 commented on eth/stagedsync/stage_log_index.go
> +	pruneTo := cfg.prune.Receipts.PruneTo(s.ForwardProgress)
just change the pruneTo value

2022-08-09 12:52 UTC, Giulio2002 requested changes

2022-08-09 12:52 UTC, Giulio2002 commented on params/config.go
> +func Eth2DeployBlockNumber(c *ChainConfig) uint64 {
return uint64 as a pointer and return nil if it does not exist for a specific chain config

2022-08-15 13:41 UTC, closed without merging