cleaned up storage and retrieval of state sync receipts
ledgerwatch/erigon pull request #5379
Opened 2022-09-15 15:57 UTC by enriavil1

- Now instead of retrieving one the bor state sync receipt by:
- 1. retrieving all receipt
- 2. deriving the bor receipt from all receipts

- We now execute the receive and derive all its fields at execution and then store it in our db, so bor receipt retrieval is just fetching it in our db and returning  the bor receipt without having to fetch all other receipts in our db.

- I have also changed the type of bor receipt from `types.ReceiptForStorage` which served no purpose other than wrapping a `types.Receipt`, but whenever we returned a bor receipt we returned the `types.Receipt`

2022-09-16 02:38 UTC, AskAlexSharov requested changes

2022-09-16 02:38 UTC, AskAlexSharov commented on core/rawdb/bor_receipts.go
> +		return nil, err
add context to this error - so we know that this error came from `ReadBorReceipt` and witch which params.

2022-09-16 02:38 UTC, AskAlexSharov commented on core/rawdb/bor_receipts.go
> +		log.Crit("Failted to read bor receipt", "err", err)
what does it logically mean - "error is important but we can ignore it"?

2022-09-21 16:40 UTC, 0xKrishna approved these changes

2022-09-22 03:47 UTC, AskAlexSharov requested changes

2022-09-22 03:47 UTC, AskAlexSharov commented on cmd/rpcdaemon/commands/eth_api.go
> +	header, err := api._blockReader.HeaderByHash(context.Background(), tx, hash)
1. this is de-optimization: read header is slower than read headerNumber (more requests, need parse rlp, allocate header object, etc...)
2. we fill `kv.HeaderNumber` table for all blocks - even for blocks in snapshots. see `eth/stagedsync/stage_snapshots.go: Load(tx, kv.HeaderNumber,`. it means we don't need `_blockReader` to get block number by block hash.

2022-09-22 03:49 UTC, AskAlexSharov commented on cmd/rpcdaemon/commands/eth_api.go
> +	header, err := api._blockReader.HeaderByHash(context.Background(), tx, hash)
3. we store this index in db - because this index is small enough.

2022-09-23 06:30 UTC, 0xKrishna commented on core/blockchain.go
> +	stateSyncReceipt := &types.Receipt{}
Use
```var stateSyncReceipt *types.Receipt```
Otherwise it will always pass this check
```		if stateSyncReceipt != nil {```

2022-09-23 06:59 UTC, 0xKrishna commented on core/blockchain.go
> +	stateSyncReceipt := &types.Receipt{}
Okay, This will create other problems, Need to think something else.

2022-09-23 07:00 UTC, 0xKrishna commented on core/blockchain.go
> +	stateSyncReceipt := &types.Receipt{}
This is for reference : https://github.com/maticnetwork/turbo-bor/blob/master/core/blockchain.go#L184
I guess now it makes sense why we used this flow in old version.

2022-09-23 10:13 UTC, 0xKrishna approved these changes

2022-09-26 08:25 UTC, AskAlexSharov approved these changes

2022-09-27 10:39 UTC, merged

2022-09-28 08:17 UTC, Zorato commented
Hey @enriavil1, is this MR that changes DB layout that needs full erigon node re-sync from scratch or it can be applied to existing synced node (pruned/archive) without any issues?

2022-09-28 08:28 UTC, enriavil1 commented
> Hey @enriavil1, is this MR that changes DB layout that needs full erigon node re-sync from scratch or it can be applied to existing synced node (pruned/archive) without any issues?

It will change how polygon state sync logs and receipts are stored. So if you want to be able to use them then yes you need a resync.

2022-09-28 08:30 UTC, Zorato commented
Ok, thanks for fast reply!