fix nilptr genesisErr
ledgerwatch/erigon pull request #5444
Opened 2022-09-20 12:57 UTC by enriavil1

Nil ptr panic

2022-09-21 12:48 UTC, AskAlexSharov commented on eth/backend.go
> +		if genesisErr != nil && !ok {
feels weird code pattern
```
if genesisErr != nil {
   if _, ok = genesisErr.(*params.ConfigCompatError); !ok {   
      return err
   }
}
```

2022-09-22 02:59 UTC, AskAlexSharov requested changes
Sorry, but is meaning of this PR?
You suppress error which says: "Hey man! I see that db has another genesis! maybe you set wrong --chain parameter? maybe you set wrong --datadir parameter?" 
For me - closing eyes on this error and continue work may cause bigger problems - like writing "Goerli blocks to Mainnet database".

Or I miss-understand something?

2022-09-22 11:37 UTC, enriavil1 commented
> 



> Sorry, but is meaning of this PR? You suppress error which says: "Hey man! I see that db has another genesis! maybe you set wrong --chain parameter? maybe you set wrong --datadir parameter?" For me - closing eyes on this error and continue work may cause bigger problems - like writing "Goerli blocks to Mainnet database".
> 
> Or I miss-understand something?

I mean we are still returning the `genesisErr` saying that, but I realised that there is a case when our genesisErr causes a nil ptr reference

2022-09-26 02:12 UTC, AskAlexSharov commented
I still don't understand meaning of this PR. 
In my head - if genesis is incompatible - better fail fast instead of hiding it.

2022-09-26 23:07 UTC, closed without merging