[caplin] incremental improvements to p2p layer
ledgerwatch/erigon pull request #7582
Opened 2023-05-25 23:24 UTC by elee1766

we update observability in the p2p layer for handlers, and also properly encode error codes, close streams.

2023-05-25 23:44 UTC, Giulio2002 approved these changes
LGTM

2023-05-26 10:36 UTC, AskAlexSharov commented on cl/beacon/router.go
> +	r.Route("/eth", func(r chi.Router) {
REST api? Is it specified somewhere?

2023-05-26 10:39 UTC, AskAlexSharov requested changes

2023-05-26 10:39 UTC, AskAlexSharov commented on cl/sentinel/peers/peer.go
> +	p.mu.Unlock()
need defer, because fn can panic

2023-05-26 11:21 UTC, Giulio2002 commented on cl/beacon/router.go
> +package beacon
I am fine ignoring this for the time being

2023-05-26 11:21 UTC, Giulio2002 commented on cl/phase1/stages/stage_fork_choice.go
> +const minPeersForDownload = 2
so downloading blocks is different than starting the sync? why would that be?

2023-05-26 11:21 UTC, Giulio2002 commented on cl/phase1/stages/stage_fork_choice.go
> +		if isDownloading {
I think i get it so sync starts at 4 peers but will stop at 2 peers, correct?

2023-05-26 11:21 UTC, Giulio2002 commented on cmd/sentinel/sentinel/communication/send_request.go
> +		return nil, 189, err
what is 189

2023-05-26 11:21 UTC, Giulio2002 commented on cmd/sentinel/sentinel/communication/send_request.go
> +	resp.code = code[0]
lgtm here

2023-05-27 01:40 UTC, elee1766 commented on cl/sentinel/peers/peer.go
> +	p.mu.Unlock()
done

2023-05-27 23:49 UTC, Giulio2002 approved these changes

2023-05-27 23:49 UTC, Giulio2002 approved these changes

2023-05-28 00:53 UTC, AskAlexSharov approved these changes

2023-05-28 00:54 UTC, merged