Dumb sentinel
ledgerwatch/erigon pull request #8296
Opened 2023-09-27 02:07 UTC by elee1766

simplify sentinel

2023-10-05 19:12 UTC, Giulio2002 commented
Ok, so I just started syncing it on my machine

2023-10-12 07:23 UTC, AskAlexSharov requested changes
Can’t state that package is apache licensed and use gpl code. example: i see usage of erigon/common

Or move to erigon-lib (then compiler will protect you). Or add go-license linter for your package: see check_license.sh in our Makefile.

2023-10-21 22:01 UTC, Giulio2002 approved these changes

2023-10-21 22:02 UTC, Giulio2002 commented
@AskAlexSharov can you approve?

2023-10-21 23:17 UTC, merged