fix: batch close confict with flush
ledgerwatch/erigon pull request #8613
Opened 2023-10-30 06:46 UTC by yyjia

both batch.Flush() and batch.close() close channel, I think flush is not necessary to close channel

2023-10-30 08:38 UTC, AskAlexSharov requested changes
Let's also make safe to call mut.Close() multiple times (from same goroutine).
By something like 
if m.clean != nil {
m.clean()
m.clean = nil 
}

2023-10-31 01:47 UTC, yyjia commented
> Let's also make safe to call mut.Close() multiple times (from same goroutine). By something like if m.clean != nil { m.clean() m.clean = nil 

> Let's also make safe to call mut.Close() multiple times (from same goroutine). By something like if m.clean != nil { m.clean() m.clean = nil }



> Let's also make safe to call mut.Close() multiple times (from same goroutine). By something like if m.clean != nil { m.clean() m.clean = nil }

Thanks for the guidance

2023-10-31 01:48 UTC, yyjia commented
> Let's also make safe to call mut.Close() multiple times (from same goroutine). By something like if m.clean != nil { m.clean() m.clean = nil }

Thanks for the guidance

2023-11-01 02:08 UTC, AskAlexSharov approved these changes

2023-11-01 02:08 UTC, merged