added snapshot sync diagnostic information, updated diagnostic channel
ledgerwatch/erigon pull request #8645
Opened 2023-11-04 08:51 UTC by dvovk

2023-11-06 14:26 UTC, mh0lt requested changes

2023-11-06 14:26 UTC, mh0lt commented on diagnostics/diagnostic.go
I think if you run like this your erigon won't close cleanly you need something like
```
for {
   select {
	case <-c.ctx.Done():
                close()
		return
	 case info := <-ch:
                d.snapshotDownload[info.StagePrefix] = info
	}
```

I'm not sure if cli.Context is cancelable - if its not you will need to look at the other code paths to find out how to set up a context which is cancelled on process exit

2023-11-06 14:26 UTC, mh0lt commented on erigon-lib/diagnostics/entities.go
Things like rates should be numeric rather than strings - so they can have additional processing applied.  So you need
Amount, and Period to be present.  Period should be a a time.Duration, you may want to normalize this on exit from the process in the diagnostics client but don't do it here.

Similarly time left should be a duration.

2023-11-06 14:26 UTC, mh0lt commented on turbo/snapshotsync/snapshotsync.go
As I mentioned I've updated the code so you can just do:

diagnostics.Send(diagnostics.DownloadStatistics{}) - with no additional scaffolding.  Code should be in devel tomorrow

2023-11-07 05:36 UTC, dvovk commented on diagnostics/diagnostic.go
done

2023-11-07 05:37 UTC, dvovk commented on erigon-lib/diagnostics/entities.go
done

2023-11-07 05:39 UTC, dvovk commented on turbo/snapshotsync/snapshotsync.go
waiting for changes. I can do it as patch in next update in order to not block new functionality to users

2023-11-07 09:05 UTC, AskAlexSharov approved these changes

2023-11-07 12:50 UTC, mh0lt approved these changes

2023-11-07 12:50 UTC, merged