added logging for slow RPC requests
ledgerwatch/erigon pull request #8818
Opened 2023-11-22 15:12 UTC by dvovk

Changed distribution of httpcfg.HttpCfg to be pointer.
Added new flags:
rpc.slow.log - which is false by default, this flag need to enable logging slow RPC requests
rpc.slow.log.threshold - which is 100 by default, this flag specify slow threshold in milliseconds 
Updated rpc handler to log slow requests:
- added map[request id] {method, timestamp}
- put every request details to map above
- delete request details from map above
- added time interval check for elements in map and if time difference is more than given threshold print request id and the method
- app will print slow requests in next cases:
1. As soon as request take more than given threshold
2. Every 20 seconds if request still in process
3. After request finished and it took more than give threshold

2023-11-22 20:30 UTC, mh0lt reviewed
I don't think you need both flags, you can just add the threshold and use  threshold!=0 as the flag.

2023-11-22 20:41 UTC, mh0lt reviewed
I don't think we should run this log message 10 times per second - it will be pretty expensive I'd have thought we want to run it say once every 20 secs ?

2023-11-23 06:57 UTC, dvovk commented
> I don't think we should run this log message 10 times per second - it will be pretty expensive I'd have thought we want to run it say once every 20 secs ?
> 
> I think it makes the map logic a bit more complex. I think you should keep a start and end time and then remove it from the map once its logged.

I think frequency of log should depend on threshold value as all sense of this logs is to print slow requests which isn't finished yet. I agree that I can change logic to print slow request only on the first check

2023-11-23 07:39 UTC, AskAlexSharov requested changes

2023-11-23 13:51 UTC, dvovk commented on rpc/handler.go
> +	go func() {
if I do it it just hangs in the loop inside this coroutine and never process request

2023-11-23 14:52 UTC, dvovk commented
> I don't think you need both flags, you can just add the threshold and use threshold!=0 as the flag.

Fixed

2023-11-23 14:53 UTC, dvovk commented on rpc/handler.go
> +				ticker.Stop()
Fixed

2023-11-23 14:53 UTC, dvovk commented on rpc/handler.go
> +	quit := make(chan struct{})
Fixed

2023-11-23 14:54 UTC, dvovk commented
> > I don't think we should run this log message 10 times per second - it will be pretty expensive I'd have thought we want to run it say once every 20 secs ?
> > I think it makes the map logic a bit more complex. I think you should keep a start and end time and then remove it from the map once its logged.
> 
> I think frequency of log should depend on threshold value as all sense of this logs is to print slow requests which isn't finished yet. I agree that I can change logic to print slow request only on the first check

Fixed, added 20 second log interval

2023-11-23 15:26 UTC, AskAlexSharov commented on rpc/handler.go
> +	go func() {
Because you didn’t listen rootctx.Done()

2023-11-27 03:33 UTC, AskAlexSharov commented on rpc/handler.go
> +		rpcMethodsWhitelist: []string{"eth_call", "eth_getBlock"},
blacklist

2023-11-27 03:41 UTC, AskAlexSharov requested changes

2023-11-27 03:41 UTC, AskAlexSharov commented on rpc/handler.go
> +				if h.isRpcMethodNeedsCheck(h.diagMessage.Method) {
`isRpcMethodNeedsCheck` check it once - before starting goroutine and ticker.

2023-11-27 03:41 UTC, AskAlexSharov commented on rpc/handler.go
> +		ticker := time.NewTicker(updateThreshold)
why not `logInterval`?

2023-11-27 03:41 UTC, AskAlexSharov commented on rpc/handler.go
> +							h.logger.Warn("[Slow RPC] - request still processing", "method", h.diagMessage.Method, "Request duration", requestDuration)
let's use prefix `[rpc.slow]` - then it will be more grep-friendly

2023-11-27 03:41 UTC, AskAlexSharov commented on rpc/handler.go
> +	diagLock            sync.Mutex
looks like we don't need this lock anymore

2023-11-27 03:41 UTC, AskAlexSharov commented on rpc/handler.go
> +	slowThreshold := time.Duration(h.rpcSlowLogThreshold) * time.Millisecond
this can be done once - when parsing CLI flag.

2023-11-27 10:06 UTC, dvovk commented
@AskAlexSharov  I rethink it a bit and removed a lot of stuff, I think now it is much better

2023-11-27 10:26 UTC, AskAlexSharov requested changes

2023-11-27 10:26 UTC, AskAlexSharov commented on rpc/handler.go
> +			slowTimer := time.AfterFunc(time.Duration(h.rpcSlowLogThreshold)*time.Millisecond, func() {
really interesting. looks good for me

let's calc `time.Duration(h.rpcSlowLogThreshold)*time.Millisecond` once - when parsing cli flag.

2023-11-27 10:26 UTC, AskAlexSharov commented on rpc/handler.go
> +		if h.rpcSlowLogThreshold > 0 && h.isRpcMethodNeedsCheck(msg.Method) {
let's store result of `h.isRpcMethodNeedsCheck(msg.Method)` into local bool variable

2023-11-27 10:26 UTC, AskAlexSharov commented on rpc/handler.go
> +				h.logger.Warn("[rpc.slow] - running", "method", msg.Method)
is it possible to print request ID and request body here? (and print only ID at `finish`)

2023-11-27 11:41 UTC, dvovk commented
@AskAlexSharov changed mentioned stuff

2023-11-28 05:20 UTC, AskAlexSharov commented
did push some changes - plz review

2023-11-28 06:57 UTC, dvovk commented
> did push some changes - plz review

Looks ok

2023-11-28 09:11 UTC, AskAlexSharov approved these changes

2023-11-28 09:11 UTC, merged