e35 semaphore for building snapshots
ledgerwatch/erigon pull request #9085
Opened 2023-12-26 21:46 UTC by awskii

wip.

2023-12-27 01:16 UTC, AskAlexSharov requested changes

2023-12-27 01:16 UTC, AskAlexSharov commented on cl/antiquary/antiquary.go
> +func NewAntiquary(ctx context.Context, genesisState *state.CachingBeaconState, validatorsTable *state_accessors.StaticValidatorTable, cfg *clparams.BeaconChainConfig, dirs datadir.Dirs, downloader pr
let's use `golang.org/x/sync/semaphore`

2023-12-27 17:25 UTC, AskAlexSharov approved these changes

2023-12-27 18:05 UTC, awskii commented
going to test this on mainnet before merge.

2024-01-02 17:09 UTC, awskii commented
[50aa834](https://github.com/ledgerwatch/erigon/pull/9085/commits/50aa8344eebb88c62afa65be05333176429151ff) worked fine, considering to merge it since same tests failed in e35 branch.

2024-01-02 20:06 UTC, merged