blob storage
ledgerwatch/erigon pull request #9310
Opened 2024-01-25 10:18 UTC by bayram98

2024-02-12 15:32 UTC, Giulio2002 requested changes

2024-02-12 15:32 UTC, Giulio2002 commented on cl/persistence/blob_storage/blob.go
> +func (a *aferoBlobStorage) BlobReader(blockRoot [32]byte) (*cltypes.BlobSidecar, error) {
Rename to ReadBlobsByBlockRoot, also this should return multiples

2024-02-12 15:32 UTC, Giulio2002 commented on cl/persistence/blob_storage/blob.go
> +func (a *aferoBlobStorage) BlobWriter(blobSidecar *cltypes.BlobSidecar) error {
Rename to WriteBlob

2024-02-12 15:34 UTC, Giulio2002 commented
One thing: as we discussed there are multiple blobs per block root

2024-02-13 10:51 UTC, bayram98 commented on cl/persistence/blob_storage/blob.go
> +func (a *aferoBlobStorage) BlobWriter(blobSidecar *cltypes.BlobSidecar) error {
Fixed

2024-02-19 20:48 UTC, Giulio2002 approved these changes

2024-02-19 20:48 UTC, merged